//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWorkBounty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Workitems = new HashSet<Workitem>();
            this.WorkitemDistributions = new HashSet<WorkitemDistribution>();
        }
    
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int UserID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> TeamUserInfoID { get; set; }
    
        public virtual Team Team1 { get; set; }
        public virtual Team Team2 { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<Workitem> Workitems { get; set; }
        public virtual ICollection<WorkitemDistribution> WorkitemDistributions { get; set; }
    }
}
