//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWorkBounty
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Teams = new HashSet<Team>();
            this.Workitems = new HashSet<Workitem>();
            this.Workitems1 = new HashSet<Workitem>();
            this.WorkItemAssignments = new HashSet<WorkItemAssignment>();
            this.WorkitemDistributions = new HashSet<WorkitemDistribution>();
            this.WorkitemHistories = new HashSet<WorkitemHistory>();
            this.WorkitemRegistrations = new HashSet<WorkitemRegistration>();
        }
    
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsActive { get; set; }
        public string InterestedKeywords { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual UserInfo UserInfo2 { get; set; }
        public virtual ICollection<Workitem> Workitems { get; set; }
        public virtual ICollection<Workitem> Workitems1 { get; set; }
        public virtual ICollection<WorkItemAssignment> WorkItemAssignments { get; set; }
        public virtual ICollection<WorkitemDistribution> WorkitemDistributions { get; set; }
        public virtual ICollection<WorkitemHistory> WorkitemHistories { get; set; }
        public virtual ICollection<WorkitemRegistration> WorkitemRegistrations { get; set; }
    }
}
