//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWorkBounty
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemAssignment
    {
        public int WorkItemAssignmentID { get; set; }
        public int WorkItemID { get; set; }
        public int UserID { get; set; }
        public string SubmissionPath { get; set; }
        public bool IsRewarded { get; set; }
        public System.DateTime SubmissionDateTime { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual Workitem Workitem { get; set; }
    }
}
